name: workflow.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          target: thumbv8m.main-none-eabihf
      - name: Add thumbv8m.main-none-eabihf target
        run: rustup target add thumbv8m.main-none-eabihf
      - name: Run Clippy
        run: cargo clippy --target thumbv8m.main-none-eabihf -- -D warnings
